SELECT CURRENT_USER();
CREATE DATABASE tcp;
SHOW DATABASES;
USE tcp;
CREATE TABLE port_info(port INT, service VARCHAR(255), PRIMARY KEY (port));
CREATE DATABASE udp;
SHOW DATABASES;
USE udp;
CREATE TABLE port_info(port INT, service VARCHAR(255), PRIMARY KEY (port));
